trigger:
- main

pool:
  name: SelfHosted  # Cambia esto al nombre de tu pool auto-hospedado

steps:
# Verificar que el directorio de fuentes existe
- script: |
    if [ -d "$(build.sourcesDirectory)" ]; then
      echo "Directorio de fuentes encontrado: $(build.sourcesDirectory)"
    else
      echo "Directorio de fuentes no encontrado. Abortando."
      exit 1
    fi
  displayName: 'Verificar directorio de fuentes'

# Archivar los archivos del proyecto (si el directorio de fuentes existe)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archivar archivos del proyecto'

# Publicar los artefactos generados
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publicar artefactos'
